---
title: "Effects of covariance on R0"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For our model, 
$$ R_0 = \frac{c \frac{\lambda}{h + \lambda} S}{\alpha + \gamma + \mu}, $$
where $c$ is the contact rate between susceptible and infected hosts, $\lambda$ is the shedding rate from infected hosts (which determines the probability of infection, given contact), $\alpha$ is the infection-induced mortality rate, $\gamma$ is the recovery rate, and $\mu$ is the natural background death rate.
If we assume that there is (co)variance in (between) either $c$, $\lambda$, or $\alpha$, how does that change the expected value of $R_0$?

In so doing, $R_0$ becomes a random variable, and we can estimate the moments of a random variable using a Taylor expansion. 
In particular, using the Taylor expansion of the function $f(x)$ around the point $\bar{x}$, we can compute the expectation of $f(x)$ as:
\begin{align*}
E[f(x)] &= E[f(\bar{x}) + f'(\bar{x})(x-\bar{x}) + \frac{1}{2}f''(\bar{x})(x-\bar{x})^2] \\
E[f(x)] &= f(\bar{x}) + f'(\bar{x})E[(x-\bar{x})] + \frac{f''(\bar{x})}{2}E[(x-\bar{x})^2].
\end{align*}
However, $E[(x-\bar{x})] = 0$ and $E[(x-\bar{x})^2] = \sigma_x^2$ (the variance in $x$). 
Thus, 
$$ E[f(x)] = f(\bar{x}) + \frac{f''(\bar{x})}{2} \sigma_x^2$$
So, for the case where $f = R_0$ and $x = c$, we have 
\begin{equation}
E[R_0(c)] = R_0(\bar{c}) + \frac{R_0''(\bar{c})}{2}\sigma_c^2 = R_0(\bar{c}).
\end{equation}
This is because $R_0''(\bar{c}) = 0$ because $R_0$ is linear in $c$. 
Biologically, this implies that variation in $c$ has no effect on the expected fitness of a pathogen. 

For the case where $x = \lambda$, however, we get 
\begin{equation}
E[R_0(\lambda)] = R_0(\bar{\lambda}) + \frac{R_0''(\bar{\lambda})}{2}\sigma_\lambda^2 = R_0(\bar{\lambda}) - \frac{h}{\bar{\lambda}(h+\bar{\lambda})^2}R_0(\bar{\lambda})\sigma_\lambda^2 = R_0\left(\bar{\lambda}\right)\left(1-\frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}\sigma_\lambda^2\right)
\end{equation}
Biologically, this implies that variation in $\lambda$ *reduces* the expected fitness of a pathogen because pathogen strains with low shedding drag average pathogen fitness down more than strains with high shedding can increase it.

For the case where $x = \alpha$, we get 
\begin{equation}
E[R_0(\alpha)] = R_0(\bar{\alpha}) + \frac{R_0''(\bar{\alpha})}{2}\sigma_\alpha^2 = R_0(\bar{\alpha}) + \frac{1}{(\bar{\alpha}+\gamma+\mu)^2}R_0(\bar{\alpha})\sigma_\alpha^2 = R_0\left(\bar{\alpha}\right)\left(1 + \frac{\sigma_\alpha^2}{\left(\bar{\alpha}+\gamma+\mu\right)^2}\right)
\end{equation}
Biologically, this implies that variation in $\alpha$ *increases* the expected fitness of a pathogen because pathogen strains with low virulence increase average pathogen fitness more than strains with high virulence decrease it.

To consider the effects of covariance among parameters, we use the multivariate Taylor expansion, 
\begin{align*}
E[f(x,y)] = &f(\bar{x},\bar{y}) + f_x(\bar{x},\bar{y})E[x-\bar{x}] + f_y(\bar{x},\bar{y})E[y-\bar{y}] \\
& + \frac{1}{2}\left(f_{xx}(\bar{x},\bar{y})E[(x-\bar{x})^2] + 2f_{xy}(\bar{x},\bar{y})E[(x-\bar{x})(y-\bar{y})]+ f_{yy}(\bar{x},\bar{y})E[(y-\bar{y})^2]\right)
\end{align*}

As before, $E[x-\bar{x}] = 0$ and $E[y-\bar{y}] = 0$, $E[(x-\bar{x})^2] = \sigma_x^2$ (the variance in $x$) and $E[(y-\bar{y})^2] = \sigma_y^2$ (the variance in $y$), and $E[(x-\bar{x})(y-\bar{y})] = \text{cov}(x,y)$ Thus,
$$ E[f(x,y)] = f(\bar{x},\bar{y}) + \frac{1}{2}\left(f_{xx}(\bar{x},\bar{y})\sigma_x^2 + 2f_{xy}(\bar{x},\bar{y})\text{cov}(x,y)+ f_{yy}(\bar{x},\bar{y})\sigma_y^2\right)$$
If there is covariance between contact rate $c$ and shedding rate (infectiousness) $\lambda$ then the expected value of $R_0$ is
\begin{align} 
E[R_0(c,\lambda)] &= R_0\left(\bar{c},\bar{\lambda}\right) + \frac{1}{2}\left(\frac{2h}{\bar{c}\bar{\lambda}(h+\bar{\lambda})}R_0\left(\bar{c},\bar{\lambda}\right)\text{cov}(c,\lambda) - \frac{2h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}R_0\left(\bar{c},\bar{\lambda}\right)\sigma_\lambda^2\right) \\
&= R_0\left(\bar{c},\bar{\lambda}\right)\left(1+\frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)}\left(\frac{\text{cov}(c,\lambda)}{\bar{c}} - \frac{\sigma_\lambda^2}{h+\bar{\lambda}}\right)\right).
\end{align}
From this expression, the effect of covariance depends on its sign. 
In particular, if contact rate and infectiousness positively covary (so that the individuals with the highest contact rate are also the most infectious), then covariation offsets the negative effect of variation in shedding observed in equation (2) above and it is possible that variation will increase the expected $R_0$.
If, however, the two traits negatively covary, then covariation will greatly reduce the expected $R_0$, as the negative covariation amplifies the negative effect of variation in shedding.

If there is covariation between contact rate $c$ and virulence $\alpha$, then the expected value of $R_0$ is
\begin{align}
E[R_0(c,\alpha)] &= R_0\left(\bar{c},\bar{\alpha}\right) + \frac{1}{2}\left(-\frac{2}{\bar{c}\left(\bar{\alpha}+\gamma+\mu\right)}R_0\left(\bar{c},\bar{\alpha}\right)\text{cov}(c,\alpha) + \frac{2}{\left(\bar{\alpha}+\gamma+\mu\right)^2}R_0\left(\bar{c},\bar{\alpha}\right)\sigma_\alpha^2\right) \\
&= R_0\left(\bar{c},\bar{\alpha}\right)\left(1 + \frac{1}{\bar{\alpha}+\gamma+\mu}\left(\frac{\sigma_\alpha^2}{\bar{\alpha}+\gamma+\mu} - \frac{\text{cov}(c,\alpha)}{\bar{c}}\right)\right).
\end{align}
From this expression, the effect of covariance between contact rate and virulence depends critically on its sign. 
In particular, if contact rate and virulence negatively covary, so that the individuals with the highest contact rate have the lowest virulence (and thus the longest infectious period), then the expected $R_0$ will be much higher than the value at the $R_0$ evaluated at the mean $\bar{c}$ and $\bar{\alpha}$. 
In this case, covariation amplifies the positive effect of variation in virulence observed in equation (3) above.
If, however, the two traits positive covary, then it is possible that covariation will decrease the expected $R_0$, as the positive covariation offsets the positive effect of variation in virulence.

If there is covariation between shedding rate $\lambda$ and virulence $\alpha$, then the expected value of $R_0$ is 
\begin{align*}
E[R_0(\lambda,\alpha)] = R_0\left(\bar{\lambda},\bar{\alpha}\right) + \frac{1}{2}(&-\frac{2h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}R_0\left(\bar{\lambda},\bar{\alpha}\right)\sigma_\lambda^2 - \frac{2h}{\bar{\lambda}\left(h+\bar{\lambda}\right)\left(\bar{\alpha}+\gamma+\mu\right)}R_0\left(\bar{\lambda},\bar{\alpha}\right)\text{cov}(\lambda,\alpha) \\
&+ \frac{2}{\left(\bar{\alpha}+\gamma+\mu\right)^2}R_0\left(\bar{\lambda},\bar{\alpha}\right)\sigma_\alpha^2)
\end{align*}

\begin{equation}
E[R_0(\lambda,\alpha)] = R_0\left(\bar{\lambda},\bar{\alpha}\right) \left(1 - \frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}\sigma_\lambda^2 - \frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)\left(\bar{\alpha}+\gamma+\mu\right)}\text{cov}(\lambda,\alpha) + \frac{1}{\left(\bar{\alpha}+\gamma+\mu\right)^2}\sigma_\alpha^2\right)
\end{equation}

It is clear that the effect of covariation is most difficult to predict here, as the effect of either positive or negative covariation between shedding and virulence will depend on the variance in both traits. 
For example, if the variation in $\lambda$ is small and there is negative covariation between $\lambda$ and $\alpha$ (so that individuals with the highest shedding have the longest infections), then covariation will increase the expected $R_0$.
However, high variation in $\lambda$ could counteract that. 
On the other hand, if the variation in $\alpha$ is small and there is positive covariation between $\lambda$ and $\alpha$ (so that there is a trade-off between virulence and shedding), then covariation will decrease the expected $R_0$.
However, high variation in $\alpha$ could counteract that.

If there is covariation between virulence $\alpha$ and recovery rate $\gamma$, then the expected value of $R_0$ is 
\begin{align*}
E[R_0(\alpha,\gamma)] &= R_0\left(\bar{\alpha},\bar{\gamma}\right) + \frac{1}{2}\left(\frac{2}{(\bar{\alpha} + \bar{\gamma} + \mu)^2} R_0\left(\bar{\alpha},\bar{\gamma}\right) \sigma_\alpha^2 + \frac{4}{(\bar{\alpha} + \bar{\gamma} + \mu)^2} R_0\left(\bar{\alpha},\bar{\gamma}\right) \text{Cov}(\alpha,\gamma) + \frac{2}{(\bar{\alpha} + \bar{\gamma} + \mu)^2} R_0\left(\bar{\alpha},\bar{\gamma}\right) \sigma_\gamma^2 \right) \\
&= R_0\left(\bar{\alpha},\bar{\gamma}\right) \left(1 + \frac{1}{(\bar{\alpha} + \bar{\gamma} + \mu)^2}\left(\sigma_\alpha^2 + 2\text{Cov}(\alpha,\gamma) + \sigma_\gamma^2 \right)\right)
\end{align*}

Variation in both virulence and recovery tend to make the epidemic bigger, an effect that will be accentuated by positive covariation. 

Summarizing, here are the effects of variation:
\begin{align}
E[R_0(c)] &= R_0(\bar{c}), \\
E[R_0(\lambda)] &= R_0\left(\bar{\lambda}\right)\left(1-\frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}\sigma_\lambda^2\right), \\
E[R_0(\alpha)] &= R_0\left(\bar{\alpha}\right)\left(1 + \frac{\sigma_\alpha^2}{\left(\bar{\alpha}+\gamma+\mu\right)^2}\right),
\end{align}
and covariation:
\begin{align}
E[R_0(c,\lambda)] &= R_0\left(\bar{c},\bar{\lambda}\right)\left(1+\frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)}\left(\frac{\text{cov}(c,\lambda)}{\bar{c}} - \frac{\sigma_\lambda^2}{h+\bar{\lambda}}\right)\right),\\
E[R_0(c,\alpha)] &= R_0\left(\bar{c},\bar{\alpha}\right)\left(1 + \frac{1}{\bar{\alpha}+\gamma+\mu}\left(\frac{\sigma_\alpha^2}{\bar{\alpha}+\gamma+\mu} - \frac{\text{cov}(c,\alpha)}{\bar{c}}\right)\right), \\
E[R_0(\lambda,\alpha)] &= R_0\left(\bar{\lambda},\bar{\alpha}\right) \left(1 - \frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)^2}\sigma_\lambda^2 - \frac{h}{\bar{\lambda}\left(h+\bar{\lambda}\right)\left(\bar{\alpha}+\gamma+\mu\right)}\text{cov}(\lambda,\alpha) + \frac{1}{\left(\bar{\alpha}+\gamma+\mu\right)^2}\sigma_\alpha^2\right).
\end{align}

From these analyses, it is clear that the worst-case scenario for disease management would be a case where there is considerable variation in virulence among individuals and where individuals with the highest contact rates have the lowest virulence. 
The best-case scenario would be a case where there is considerable variation in shedding and where individuals with the highest shedding rates also have the lowest contact rates.